#!/usr/bin/env perl
use strict;
use Cwd;

my $case = (split /\//, getcwd())[-1];
my $rundir = get_rundir();

sub get_rundir
{
    my $lang = `grep python xmlquery`;
    my $rundir;
    if ($lang =~ /python/){
	$rundir = `./xmlquery --value RUNDIR`;
    }else{
	$rundir = `./xmlquery -value RUNDIR 2>&1`;
	if ($rundir =~ /Unknown option/){
	    $rundir = `./xmlquery -valonly RUNDIR`;
	    $rundir =~ /= (.*)/;
	    $rundir = $1;
	}
    }
    return $rundir;
     
}

my $model = "cesm";

my $greparg = shift;

$model = shift if($#ARGV>=0);

die "Could not find $rundir\n" unless(-d $rundir);

opendir(D,"$rundir");
my @logs = grep /$model\.log\.\d+\-\d+\.?/, readdir D;
#print "$model: @logs\n";
my $log = $logs[0];
# find the newest if there are more than one.
my $lage = -M "$rundir/$log";
foreach(@logs){    
    if((-M "$rundir/$_") < $lage){
	$log=$_;
	$lage = -M "$rundir/$log";
    }
	
}
if($log =~ /gz$/){
    system("zgrep \'$greparg\' $rundir/$log");
}else{
    system("grep \'$greparg\' $rundir/$log");
}
