#!/usr/bin/env perl
use strict;
use Cwd;

my $case = (split /\//, getcwd())[-1];

my $rundir = get_rundir();

sub get_rundir
{
    my $lang = `grep python xmlquery`;
    my $rundir;
    if ($lang =~ /python/){
	$rundir = `./xmlquery --value RUNDIR`;
    }else{
	$rundir = `./xmlquery -value RUNDIR 2>&1`;
	if ($rundir =~ /Unknown option/){
	    $rundir = `./xmlquery -valonly RUNDIR`;
	    $rundir =~ /= (.*)/;
	    $rundir = $1;
	}
    }
    return $rundir;
     
}

if(-d "$rundir"){
    system("ls -ltr $rundir");
    print "$rundir\n";
}else{
    print "Could not find >$rundir<\n";
}
